export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_NOTES_START = "FETCH_NOTES_START";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_ERROR = "FETCH_NOTES_ERROR";
export const SAVE_NOTES_START = "SAVE_NOTES_START";
export const SAVE_NOTES_SUCCESS = "SAVE_NOTES_SUCCESS";
export const SAVE_NOTES_ERROR = "SAVE_NOTES_ERROR";
export const CHANGE_NOTE = "CHANGE_NOTE";
export const SET_FILTER = "CHANGE_FILTER";
export const ADD_NOTE = "ADD_NOTE";
